services:
  app:
    build:
      dockerfile: ./docker/app/dockerfile.dev
    ports:
      - "3000:3000" # ホストの3000番をコンテナの3000番へ繋ぐ
    volumes:
      - cargo-registry:/usr/local/cargo/registry  # ダウンロード済みクレートのキャッシュ
      - cargo-target:/app/target     
    environment:
      - DB_USER=${DB_USER}
      - CLIENT_ID=${CLIENT_ID}
      - DB_PASS=${DB_PASS}    
      - RUST_BACKTRACE=1
  surrealdb:
    image: 
      surrealdb/surrealdb:latest
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command:
      - start
      - --user
      - ${DB_USER}
      - --pass
      - ${DB_PASS}
    ports:
      - "8000:8000"
    volumes:
      - surreal_data:/data
  redis:
    image:
      redis:latest
    command:
     - redis-server
     - /usr/local/etc/redis.conf
     - --requirepass
     - ${REDIS_PASS}
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    environment:
      - REDIS_PASS=${REDIS_PASS}
    ports:
      - "6379:6379"
volumes:
  surreal_data: # ボリュームの定義
  cargo-registry: # 外部ボリュームとして作成
  cargo-target: